export const ATLAS_ORDER = [
  "red_0",
  "red_1",
  "red_2",
  "red_3",
  "red_4",
  "red_5",
  "red_6",
  "red_7",
  "red_8",
  "red_9",
  "red_skip",
  "red_reverse",
  "red_draw2",
  "blue_0",
  "blue_1",
  "blue_2",
  "blue_3",
  "blue_4",
  "blue_5",
  "blue_6",
  "blue_7",
  "blue_8",
  "blue_9",
  "blue_skip",
  "blue_reverse",
  "blue_draw2",
  "green_0",
  "green_1",
  "green_2",
  "green_3",
  "green_4",
  "green_5",
  "green_6",
  "green_7",
  "green_8",
  "green_9",
  "green_skip",
  "green_reverse",
  "green_draw2",
  "yellow_0",
  "yellow_1",
  "yellow_2",
  "yellow_3",
  "yellow_4",
  "yellow_5",
  "yellow_6",
  "yellow_7",
  "yellow_8",
  "yellow_9",
  "yellow_skip",
  "yellow_reverse",
  "yellow_draw2",
  "wild",
  "wild_draw4",
  "back",
];

// Precomputed lookup for fast atlas-index resolution.
// `CardAtlasView` runs once per visible card per render, so we want
// O(1) instead of O(n) `indexOf` on the 56-entry ATLAS_ORDER array.
export const ATLAS_INDEX: ReadonlyMap<string, number> = new Map(
  ATLAS_ORDER.map((id, idx) => [id, idx]),
);

export const AVATAR_SYMBOLS = [
  { id: "tiger", emoji: "🐯", name: "Neon Tiger" },
  { id: "dragon", emoji: "🐲", name: "Cosmic Dragon" },
  { id: "phoenix", emoji: "🦅", name: "Golden Phoenix" },
  { id: "panda", emoji: "🐼", name: "Shadow Panda" },
  { id: "wolf", emoji: "🐺", name: "Alpha Wolf" },
  { id: "owl", emoji: "🦉", name: "Cyber Owl" },
  { id: "fox", emoji: "🦊", name: "Spectral Fox" },
  { id: "shark", emoji: "🦈", name: "Deep Shark" },
];

export const AVATAR_THEMES = [
  { id: "rose", name: "Neon Rose", primary: "hsl(358, 75%, 55%)", secondary: "hsl(340, 75%, 45%)" },
  {
    id: "sapphire",
    name: "Electric Sapphire",
    primary: "hsl(208, 85%, 52%)",
    secondary: "hsl(220, 80%, 42%)",
  },
  {
    id: "aurora",
    name: "Emerald Aurora",
    primary: "hsl(148, 65%, 45%)",
    secondary: "hsl(160, 60%, 35%)",
  },
  { id: "sol", name: "Golden Sol", primary: "hsl(46, 95%, 55%)", secondary: "hsl(35, 90%, 45%)" },
  {
    id: "nebula",
    name: "Purple Nebula",
    primary: "hsl(280, 75%, 55%)",
    secondary: "hsl(260, 70%, 45%)",
  },
];
